# Application Properties
spring:
  application:
    name: Liquibase Demo
  # Jpa Properties
  datasource:
    url: jdbc:mysql://localhost:3306/liquibasedemo
    #url: ${spring.datasource.url}
    username: root
    password: ${spring.datasource.password}

  jpa:
    hibernate:
      ddl-auto: none

  # Liquibase properties
  devtools:
    restart:
      enabled: true
  liquibase:
    contexts: dev
    change-log: classpath:db/db.changelog-master.xml

## Server Properties
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: ["health","info"]
  endpoint:
    auditevents:
      enabled: true

